### ISSUE TITLE
To-do list and locales

### ISSUE THREAD

**Issue by JohnFai91** [20Nick/OPMT#1]
Hello, I'm an F-Droid user and I enjoy this simple but fun game. I've discovered some improvements that you can make.

# Issues
## 1. Dark theme confusing in game
The dark background, black pieces, and the board are all in black, making it very hard to spot what is happening, it took me a few games to figure out that the black pieces are there because of my viewing angles.
### Suggestions
1. Make the pieces in bright colours such as red and blue.
2. Support light theme with boards changing colour accordingly (dark theme -> white board, light theme -> black board)
## 2. To-do list add into "project"
I was thinking of typing up the issues and then I found lines of code of what I am thinking but they are not in the readme.md.
### Suggestions
1.  Use the "Projects" tab like [this](https://github.com/JohnFai91/com.jason.kslo/projects/5) without needing to update the readme.md every time you release a version.
## 3. Locales
The strings in your app are empty now and the words are hard-coded into the textboxes but it should be in the strings.xml for future use like repeating words and translating.
### Suggestions
1. Move words into the "strings.xml" under "values"
2. I can help translate the app in Traditional Chinese (zh-rHK, zh-rTW)

**Comment by JohnFai91** [comment]
I've created a [pull request](#2) #2 for all those mentioned above:
**Bold words** are mentioned in the post above
1. Support various screen sizes (trim board.png and remake layout of the activity_game.xml) and **add strings.xml**
1. Resolve warnings and **replace words with strings**
1. Resolve typos in README.md

**Comment by 20Nick** [comment]
I just wanted to say thank you for contributing and trying out this game.

I think moving the to-do list into the projects in a great idea and I will do.

Having multiple themes is something that I am planning on. I think having the default theme to have more bright colors is good idea and something I should implement.
